export enum TipoSolcitud{
    CAMBIODEASESOR = 1,
    CAMBIODEJURADO = 2,
    CAMBIODETITULO = 3,
    FECHADESUSTENTACION = 4,
    REVISIONPRESENCIAL = 5,
    ANULACIONDETEMADETESIS = 6,
    SOLICITUDBACHILLER=7,
    SOLICITUDTITULO=8
}

export const tipoDescripcion: Record<TipoSolcitud, string> = {
    [TipoSolcitud.CAMBIODEASESOR]: "SOLICITUD DE CAMBIO DE ASESOR",
    [TipoSolcitud.CAMBIODEJURADO]: "SOLICITUD DE CAMBIO DE JURADO",
    [TipoSolcitud.CAMBIODETITULO]: "SOLICITUD DE CAMBIO DE TITULO",
    [TipoSolcitud.FECHADESUSTENTACION]: "SOLICITUD DE FECHA DE SUSTENTACION",
    [TipoSolcitud.REVISIONPRESENCIAL]: "SOLICITUD DE REVISION PRESENCIAL",
    [TipoSolcitud.ANULACIONDETEMADETESIS]: "SOLICITUD DE ANULACION DE TESIS",
    [TipoSolcitud.SOLICITUDBACHILLER]: "SOLICITUD DE BACHILLER",
    [TipoSolcitud.SOLICITUDTITULO]: "SOLICITUD DE TITULO",
  };