version: "3"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database-sql
    restart: always
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Unu#2023
    networks:
    - td2023
  postgres:
    image: postgres:alpine3.14
    container_name: database-postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=Unu#2023
    ports:
    - 5433:5432
    networks:
    - td2023
  mongo:
    image: mongo:5.0.2
    container_name: database-mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
    - 27018:27017
    networks:
    - td2023 
  mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Unu#2023
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - td2023 
  redis:
    image: redis:6.2.6
    command: --requirepass Unu#2023
    container_name: database-redis
    restart: always
    environment:
    - REDIS_PASSWORD=Unu#2023
    ports:
    - 6379:6379
    networks:
    - td2023 
  broker:
    image: johnnypark/kafka-zookeeper:2.6.0
    container_name: service-broker
    restart: always
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
    - ADVERTISED_HOST=127.0.0.1
    - NUM_PARTITIONS=3
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
    - td2023
  facultad:
    container_name: ms-facultad
    build:
      context: ./API.Facultad
    depends_on:
      - sql
    ports:
      - "5001:80"
      - "7001:443"
    networks:
    - td2023
  docente:
    container_name: ms-docente
    build:
      context: ./API.Docentes
    depends_on:
      - postgres
    ports:
      - "5002:80"
      - "7002:443"
    networks:
    - td2023
  expediente:
    container_name: ms-expediente
    build:
      context: ./API.Expedientes
    depends_on:
      - mongo
    ports:
      - "5003:80"
      - "7003:443"
    networks:
    - td2023
  gateway:
    build:
      context: ./API.Presentacion
    ports:
      - "3001:3001"
    depends_on:
      - docente
      - facultad
      - expediente
networks:
  td2023:
    name: ms-unu

