// <auto-generated />
using System;
using Api.Facultad.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Facultad.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231217213301_FacultadV6")]
    partial class FacultadV6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api.Facultad.Domain.Entities.Escuela", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FacultadId")
                        .HasColumnType("bigint")
                        .HasColumnName("FacultadId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId");

                    b.ToTable("Escuela", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FacultadId = 1L,
                            Nombre = "ESCUELA DE INGENIERIA CIVIL"
                        },
                        new
                        {
                            Id = 2L,
                            FacultadId = 1L,
                            Nombre = "ESCUELA DE INGENIERIA DE SISTEMAS"
                        },
                        new
                        {
                            Id = 3L,
                            FacultadId = 2L,
                            Nombre = "ESCUELA DE ENFERMERIA"
                        },
                        new
                        {
                            Id = 4L,
                            FacultadId = 2L,
                            Nombre = "ESCUELA DE PSICOLOGIA"
                        },
                        new
                        {
                            Id = 5L,
                            FacultadId = 3L,
                            Nombre = "ESCUELA DE AGRONOMIA"
                        },
                        new
                        {
                            Id = 6L,
                            FacultadId = 3L,
                            Nombre = "ESCUELA DE INGENIERIA AGROINDUSTRIAL"
                        },
                        new
                        {
                            Id = 7L,
                            FacultadId = 4L,
                            Nombre = "ESCUELA DE INGENIERIA FORESTAL"
                        },
                        new
                        {
                            Id = 8L,
                            FacultadId = 4L,
                            Nombre = "ESCUELA DE INGENIERIA AMBIENTAL"
                        },
                        new
                        {
                            Id = 9L,
                            FacultadId = 5L,
                            Nombre = "ESCUELA DE MEDICINA HUMANA"
                        });
                });

            modelBuilder.Entity("Api.Facultad.Domain.Entities.Facultade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("CreatedFrom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CreadoDesde");

                    b.Property<string>("Encargado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Encargado");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Eliminado");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModificadoEn");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("ModifiedFrom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModificadoDesde");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Facultad", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Dante",
                            CreatedFrom = "migration",
                            IsDeleted = false,
                            Nombre = "FACULTAD DE INGENIERIA DE SISTEMAS E INGENIERIA CIVIL"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Dante",
                            CreatedFrom = "migration",
                            IsDeleted = false,
                            Nombre = "FACULTAD DE CIENCIAS DE LA SALUD"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Dante",
                            CreatedFrom = "migration",
                            IsDeleted = false,
                            Nombre = "FACULTAD DE CIENCIAS AGROPECUARIAS"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Dante",
                            CreatedFrom = "migration",
                            IsDeleted = false,
                            Nombre = "FACULTAD DE CIENCIAS FORESTAS Y AMBIENTALES"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Dante",
                            CreatedFrom = "migration",
                            IsDeleted = false,
                            Nombre = "FACULTAD DE MEDICINA HUMANA"
                        });
                });

            modelBuilder.Entity("Api.Facultad.Domain.Entities.Escuela", b =>
                {
                    b.HasOne("Api.Facultad.Domain.Entities.Facultade", "Facultad")
                        .WithMany("Escuelas")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("Api.Facultad.Domain.Entities.Facultade", b =>
                {
                    b.Navigation("Escuelas");
                });
#pragma warning restore 612, 618
        }
    }
}
